[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/datocms/plugin-health"
  to = "/.netlify/functions/plugin-health"
  status = 200

[[redirects]]
  from = "/api/datocms/backup-status"
  to = "/.netlify/functions/backup-status"
  status = 200

[[redirects]]
  from = "/api/jobs/scheduled-backups"
  to = "/.netlify/functions/scheduledBackups"
  status = 200

[template.environment]
  DATOCMS_FULLACCESS_API_TOKEN = "Input your DatoCMS project Full Access Token"
  DATOCMS_BACKUPS_SHARED_SECRET = "superSecretToken"
